# Generated by Django 2.2 on 2021-06-29 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tips_app', '0002_hours_pool_tips_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='users',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='share_of_tips',
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_pools', to='tips_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_length', to='tips_app.User'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
