# Generated by Django 2.2 on 2021-06-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips_app', '0003_auto_20210629_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='pool_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pools', to='tips_app.User'),
        ),
    ]
