# Generated by Django 2.2 on 2021-06-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_app', '0004_auto_20210629_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='pool_users',
            field=models.ManyToManyField(null=True, related_name='pool_groups', to='tips_app.User'),
        ),
    ]
