# Generated by Django 2.2 on 2021-06-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_app', '0005_pool_pool_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='pool_users',
            field=models.ManyToManyField(related_name='pool_groups', to='tips_app.User'),
        ),
    ]
