# Generated by Django 2.2 on 2021-06-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips_app', '0006_auto_20210629_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipients',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.DeleteModel(
            name='Tips',
        ),
    ]
