# Generated by Django 2.2 on 2021-06-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips_app', '0007_auto_20210630_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='total_tips',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_recieved', to='tips_app.User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tips_shared',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
